[package]
name = "wait_n_open"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1.4"
inotify = "0.9"
anyhow = "1.0"
structopt = "0.3"
